# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: Luis Navarro Personal Site
# Website URL
baseURL: 'https://luisenavarro.com/'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 40
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>

# Ensure ignoreFiles is commented out or does not include .html files
# ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]

# Permalinks structure is correct for your use case
permalinks:
  authors: '/author/:slug/'

# Ensure HTML output is correctly configured for all content types
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
  page: [HTML]  # Add this line to ensure pages output as HTML
  taxonomy: [HTML, RSS]
  term: [HTML]

# Optional: Specify output formats explicitly if needed
outputFormats:
  HTML:
    mediaType: text/html
    baseName: index
    isPlainText: false
    noUgly: true

# Imaging settings
imaging:
  resampleFilter: lanczos
  quality: 100
  anchor: smart
  exif:
    disableDate: false
    disableLatLong: false
    excludeFields: ""
    includeFields: ""

timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
#  End 
